routes/web.php
    Route::get('allotments/get_all_item_details_specifications/{employee_id}', 'AllotmentController@getAllItemDetailsSpecifications')->name('allotments.get_all_item_details_specifications');
    Route::post('allotment/merge_duplicate_items/{employee_id}/{employee_type}','AllotmentController@mergeDuplicateItems')->name('merge_duplicate_items');
    // Route::resource('external_employee', 'ExternalEmployeeController');
    Route::prefix('allotments')->group(function () {
        Route::resource('external_employee', 'ExternalEmployeeController');
    });
    Route::get('get_external_employee_ajax', 'ExternalEmployeeController@getExternalEmployeeAjax')->name('external_employee.get_external_employee_ajax');
    Route::post('get_external_employees_search', 'ExternalEmployeeController@getExternalEmployeesSearch')->name('external_employee.get_external_employees_search');
    Route::get('get_external_employee/{id}', 'ExternalEmployeeController@getExternalEmployee')->name('get_external_employee');
    Route::post('get_motamed', 'AllotmentController@getMotamed')->name('get_motamed');

    Route::resource('item_return_requests', 'ItemReturnRequesdController');
    Route::get('item_return_requests_completed','ItemReturnRequesdController@completed')->name('item_return_requests.completed');
    Route::get('item_return_requests_inprogress','ItemReturnRequesdController@inprogress')->name('item_return_requests.inprogress');
    Route::post('item_return_requests/conformation/{id}', 'ItemReturnRequesdController@itemReturnConformation')->name('item_return_requests.conformation');
    Route::post('attach_file_requested_item', 'ItemReturnRequesdController@attachFileAndSend')->name('attach_file_requested_item');
    Route::post('replace_return_requests_file', 'ItemReturnRequesdController@replaceAttachedFile')->name('replace_return_requests_file');


    Route::group(['prefix' => 'fece5s', 'as' => 'fece5s.'], function () {
        Route::post('attach_file_and_send', 'Fece5Controller@attachFileAndSend')->name('attach_file_and_send');
        Route::post('replace_attached_file', 'Fece5Controller@replaceAttachedFile')->name('replace_attached_file');
        Route::get('conformation/{id?}/{status?}', 'Fece5Controller@fece5Conformation')->name('conformation');
        Route::post('reject_fece5/{id?}', 'Fece5Controller@rejectFece5')->name('reject_fece5');
    });

    Route::post('export_excel','ReportController@exportExcel')->name('export_excel');

    // Route::group(['prefix' => 'items', 'as' => 'items.'], function() {
    //     Route::get('/', 'ItemDetailsController@index')->name('index');
    //
    // });
    // Route::resource('end_items_details', 'ItemDetailsController');

    // Settings

    // Unit
    Route::resource('units', 'UnitController');
    Route::resource('contractor_company', 'ContractorCompanyController');
    Route::resource('contracts', 'ContractController');
    Route::get('contracts_show_item/{id?}', 'ContractController@contractsShowItem')->name('contracts.show_item');
    Route::resource('contract_type', 'ContractTypeController');
    Route::resource('contract_items', 'ContractItemsController');

    // Department
    Route::resource('departments', 'DepartmentController');
    Route::get('get_departments', 'DepartmentController@getDepartment')->name('get_departments');
    Route::resource('external_departments', 'ExternalDepartmentController');
    

    // Sub Categories Keys
    Route::get('sub_categories_keys/create/{sub_categories_id?}', 'SubCategoriesKeyController@create')->name('sub_categories_keys.create');
    Route::resource('sub_categories_keys', 'SubCategoriesKeyController')->except('create');
    Route::get('get_sub_categories_keys/{sub_category_id?}/{data?}', 'SubCategoriesKeyController@getSubCategoriesKeys')->name('sub_categories_keys.get_sub_categories_keys');
    Route::get('get_sub_categories_select_options/{sub_category_id?}/{data?}', 'SubCategoriesKeyController@getSubCategoriesSelectOptions')->name('sub_categories_keys.get_sub_categories_select_options');
    Route::get('get_item_details_by_specifications/{sub_category_id?}', 'SubCategoriesKeyController@getItemDetailsBySpecifications')->name('sub_categories_keys.get_item_details_by_specifications');

    // Vendor
    Route::resource('vendors', 'VendorController');

    // Main Category
    Route::resource('main_categories', 'MainCategoryController');
    Route::post('get_sub_categories', 'MainCategoryController@getSubCategories')->name('get_sub_categories');
    Route::post('get_end_categories', 'MainCategoryController@getEndCategories')->name('get_end_categories');
    Route::resource('sub_categories', 'SubCategoryController');
    Route::resource('end_categories', 'EndCategoryController');

    Route::post('get_setting_modal_view', 'ItemDetailsController@getSettingModalView')->name('get_setting_modal_view');

    // testing the new items format
    // Route::get('item_details/create_new_items', 'ItemDetailsController@createNewItems')->name('item_details.create_new_items');
    Route::get('get_categories', 'ItemDetailsController@getCategories')->name('get_categories');
    Route::post('get_related_categories', 'ItemDetailsController@getRelatedCategories')->name('get_related_categories');
    Route::get('get_all_employees', 'EmployeeController@getAllEmployees')->name('get_all_employees');
    Route::get('get_employees_by_dep/{department_id}', 'EmployeeController@getEmployeesByDep')->name('get_all_employees');
    Route::get('get_employees_by_father/{father_name}', 'EmployeeController@getEmployeesByFather')->name('get_employees_by_father');
    Route::get('get_employees_by_name_father/{employee_type?}/{name?}/{father_name?}', 'EmployeeController@getEmployeesByNameFather')->name('get_employees_by_name_father');

    Route::resource('item_details', 'ItemDetailsController');
    Route::get('get_item_details', 'ItemDetailsController@getItemDetails')->name('get_item_details');
    Route::get('get_item_details_ajax', 'ItemDetailsController@getItemDetailsAjax')->name('get_item_details_ajax');
    Route::post('item_details_search', 'ItemDetailsController@itemDetailsSearch')->name('item_details_search');
    Route::get('get_item_details_consumable', 'ItemDetailsController@getItemDetailsConsumable')->name('get_item_details_consumable');

    // check if all requested items alloted based on item_details_id
    Route::get('fece9_all_items_alloted/{fece9_id}/{item_details_id}', 'ItemDetailsController@fece9AllItemsAlloted')->name('item_details.fece9_all_items_alloted');

    Route::resource('item_details_specifications', 'ItemDetailsSpecificationsController');
    Route::get('edit_item_details_specifications/{id}/', 'ItemDetailsSpecificationsController@editItemDetailsSpecifications')->name('item_details_specifications.edit_item_details_specifications');
    Route::get('get_item_details_specifications/{item_details_id}/{fece9_id?}', 'ItemDetailsSpecificationsController@getItemDetailsSpecifications')->name('item_details_specifications.get_item_details_specifications');
    Route::get('get_item_details_specifications_axios/{item_details_id}', 'ItemDetailsSpecificationsController@getItemDetailsSpecificationsAxios')->name('item_details_specifications.get_item_details_specifications_axios');
    Route::post('item_details_attach_file_and_send', 'ItemDetailsSpecificationsController@attachFileAndSend')->name('item_details_attach_file_and_send');
    Route::get('edit_item/{id}/', 'AllotmentController@editItem')->name('edit_item');
    Route::put('update_item/{id}/', 'AllotmentController@update')->name('update_item');
    Route::resource('requested_items', 'RequestedItemController');


    Route::get('requested_item_details/{id}', 'RequestedItemController@create')->name('requested_item_details');
    Route::get('requested_items_accept', 'RequestedItemController@accept')->name('requested_items_accept');
    Route::get('requested_items_reject', 'RequestedItemController@reject')->name('requested_items_reject');
    // Route::get('requested_item_details_index', 'ItemDetailsController@indexRequestedItem')->name('requested_item_details_index');

    // Items Informations
    Route::get('items_basic_informations', 'MainCategoryController@itemsBasicInformations')->name('items_basic_informations');

    //employee
    Route::post('employee/{name?}', 'EmployeeController@ajaxSearch')->name('get_employee');

    Route::post('employee_axios/{name?}', 'EmployeeController@axiosSearch')->name('get_employee_axios');
    Route::post('get_employee_father_axios/{father_name?}', 'EmployeeController@getEmployeeFatherAxios')->name('get_employee_father_axios');

    // Route::group(['prefix' => 'items_basic_informations', 'as' => 'items_basic_informations.'], function() {
    //     Route::get('/', 'MainCategoryController@index')->name('index');
    //
    // });
    Route::post('check_password','UserController@checkPassword')->name('check_password');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('permissions', 'PermissionsController');
    Route::resource('item_report', 'ReportController');
    Route::get('item_report_details', 'ReportController@itemDetailsReport')->name('item_report_details');
    //ajax serach for item details
    Route::post('select2_search_ajax/{name?}', 'ReportController@ajaxSearch')->name('select2_search_ajax');
    Route::post('item_axios/{name?}', 'ReportController@axiosSearch')->name('item_axios');
    Route::post('available_to_aloot', 'ItemDetailsSpecificationsController@availableToAloot')->name('available_to_aloot');
    Route::post('attach_file_and_send', 'EmployeeAttachmentController@attachFileAndSend')->name('employee_attachment.attach_file_and_send');
    
});
// Route::get('purchased_items', 'HomeController@purchasedItems')->name('items.purchased');



// Route::get('fece9/index', 'HomeController@fess9Index');

app/ExternalDepartment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\SoftDeletes;
class ExternalDepartment extends Model
{
    use LogsActivity;
    use SoftDeletes;
    protected $table = 'external_departments';
    protected $fillable = ['name_dr','name_en','name_pa','created_at','updated_at','created_by','updated_by','deleted_at','deleted_by'];
    protected static $logAttributes = ['name_dr','name_en','name_pa','created_at','updated_at','created_by','updated_by','deleted_at','deleted_by'];
    protected static function boot()
    {
        parent::boot();

        // create a event to happen on updating
        static::updating(function($table)  {
            $table->updated_by = Auth::user()->id ;
        });

        // create a event to happen on deleting
        static::deleting(function($table) {
            $table->deleted_by = Auth::user()->id ;
        });

        // create a event to happen on saving
        static::saving(function($table)  {
            $table->created_by = Auth::user()->id ;
        });
    }
}

app/Http/Controllers/ExternalDepartmentController.php
<?php

namespace App\Http\Controllers;

use App\ExternalDepartment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreExternalDepartmentRequest;
use App\Http\Requests\UpdateExternalDepartmentRequest;


class ExternalDepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = ExternalDepartment::orderBy('id', 'desc')->get();
        return view('external_departments.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('external_departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreExternalDepartmentRequest $request)
    {
        ExternalDepartment::create($request->input());
        return redirect()->route('external_departments.create')->with('success', trans('global.create_successful'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $external_department=ExternalDepartment::find(decrypt($id));
        return view('external_departments.edit', compact('external_department'));    
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateExternalDepartmentRequest $request, $id)
    {
        $external_department=ExternalDepartment::find(decrypt($id));
        $external_department->update($request->input());
        return redirect()->route('external_departments.index')->with('success', trans('global.update_successful'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $external_department=ExternalDepartment::find(decrypt($id));
        $external_department->delete();
        $external_department['deleted_by']=Auth::user()->id;
        $external_department->save();
        return response()->json([
            'status'  => 'success',
            'message' => trans('global.delete_successful')
        ]);
    }
}

resources/views/external_departments/create.blade.php
@extends('layouts.master')
@section('title', trans('global.create_external_departments'))
@section('content')

<form class="m-form m-form--fit m-form--label-align-right" method="POST" action="{{route('external_departments.store')}}">
    @csrf
    <div class="m-portlet__body">
        <div class="form-group m-form__group {{$errors->has('name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_dr" value="{{old('name_dr')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_dr')}}">
            @if($errors->has('name_dr'))
                <div class="form-control-feedback">{{$errors->first('name_dr')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('name_en') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_en" value="{{old('name_en')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_en')}}">
            @if($errors->has('name_en'))
                <div class="form-control-feedback">{{$errors->first('name_en')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('name_pa') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_pa" value="{{old('name_pa')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_pa')}}">
            @if($errors->has('name_pa'))
                <div class="form-control-feedback">{{$errors->first('name_pa')}}</div>
            @endif
        </div>
    </div>
    <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
            <button type="submit" class="btn btn-primary">{{trans('global.submit')}}</button>
            <button type="reset" class="btn btn-danger">{{trans('global.cancel')}}</button>
        </div>
    </div>
</form>
@endsection

resources/views/external_departments/edit.blade.php
@extends('layouts.master')
@section('title', trans('global.edit_external_department'))
@section('content')

<form class="m-form m-form--fit m-form--label-align-right" method="POST" action="{{route('external_departments.update', encrypt($external_department->id))}}">
    @csrf
    @method('PUT')
    <div class="m-portlet__body">
        <div class="form-group m-form__group {{$errors->has('name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_dr" value="{{ $external_department->name_dr }}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_dr')}}">
            @if($errors->has('name_dr'))
                <div class="form-control-feedback">{{$errors->first('name_dr')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('name_en') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_en" value="{{ $external_department->name_en }}"  type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_en')}}">
            @if($errors->has('name_en'))
                <div class="form-control-feedback">{{$errors->first('name_en')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('name_pa') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_pa" value="{{ $external_department->name_pa }}"  type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name_pa')}}">
            @if($errors->has('name_pa'))
                <div class="form-control-feedback">{{$errors->first('name_pa')}}</div>
            @endif
        </div>
    </div>
    <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
            <button type="submit" class="btn btn-primary">{{trans('global.submit')}}</button>
            <button type="reset" class="btn btn-danger">{{trans('global.cancel')}}</button>
        </div>
    </div>
</form>
@endsection

resources/views/external_departments/index.blade.php
@extends('layouts.master')
@section('title',trans('global.external_departments'))
@section('content')
<table class="table table-striped- table-bordered table-hover table-checkable jquery-datatable" id="m_table_1">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">{{trans('global.name')}}</th>
        <th scope="col">{{trans('global.actions')}}</th>
      </tr>
    </thead>
    <tbody>

        @foreach ($data as $key => $item)
            <tr id="{{$item->id}}_tr">
                <th scope="row">{{++$key}}</th>
                <td>{{$item->$name}}</td>
                <td>
                    <a class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" href="{{ route('external_departments.edit',encrypt($item->id)) }}"><i class="la la-edit"></i></a>
                    <a href="javascript:void(0)" onclick="deleteRecord('{{route('external_departments.destroy', encrypt($item->id))}}','{{$item->id}}_tr');" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill ">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        @endforeach
    </tbody>
  </table>
@endsection
@push('create-button')
<a href="{{ route('external_departments.create') }}" class="btn btn-success m-btn m-btn--custom ">
    <span>
    <span>اضافه نمودن</span>
    <i class="la la-plus"></i>
    </span>
</a>
@endpush