routes/web.php
<?php

use Illuminate\Validation\Factory;
use App\ItemDetails;
use App\User;
use App\Employee;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ItemDetailsSpecifications;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');

    // Route::group(['prefix' => 'fece9', 'as' => 'fece9s.'], function() {
    //     Route::get('/', 'Fece9Controller@index')->name('index');
    //
    // });
    Route::group(['prefix' => 'fece9s', 'as' => 'fece9s.'], function () {
        Route::post('attach_file_and_send', 'Fece9Controller@attachFileAndSend')->name('attach_file_and_send');

        Route::get('received_create', 'Fece9Controller@receivedIndex')->name('received_create');

        Route::get('received_show/{id}', 'Fece9Controller@receivedShow')->name('received_show');


        Route::get('in_progress', 'Fece9Controller@inProgress')->name('in_progress');
        Route::get('inspection_approval', 'Fece9Controller@inspectionApproval')->name('inspection_approval');

        Route::post('replace_attached_file', 'Fece9Controller@replaceAttachedFile')->name('replace_attached_file');
        
        Route::get('insepection_show/{id}', 'Fece9Controller@insepectionShow')->name('insepection_show');
        Route::post('insepection_approved', 'Fece9Controller@insepectionApproved')->name('insepection_approved');
        Route::post('inspenction_reject_fece9', 'Fece9Controller@inspectionRejectFece9')->name('inspenction_reject_fece9');
        Route::post('inspection_update', 'Fece9Controller@inspectionUpdate')->name('inspection_update');

        Route::get('completed', 'Fece9Controller@completedFece9s')->name('completed');
        Route::get('completed_show/{id}', 'Fece9Controller@completedShow')->name('completed_show');




        Route::post('item_details_status', 'Fece9Controller@Fece9ItemDetailsStatus')->name('item_details_status');
    });
    Route::get('fece9_print/{id}','Fece9Controller@printFece9')->name('fece9_print');
    Route::resource('fece9s', 'Fece9Controller');
    Route::resource('fece2s', 'Fece2Controller');
    Route::get('fece2_conformation/{id?}/{status?}', 'Fece2Controller@fece2Confirmation')->name('fece2_conformation');
    Route::post('fece2_attach_file_and_send', 'Fece2Controller@attachFileAndSend')->name('fece2_attach_file_and_send');
    Route::post('reject_fece2/{id?}', 'Fece2Controller@rejectFece2')->name('reject_fece2');
    Route::post('fece2_replace_attached_file', 'Fece2Controller@replaceAttachedFile')->name('fece2_replace_attached_file');
    Route::get('wait_meem7', 'Fece2Controller@WaitMeem7')->name('fece2s.wait_meem7');
    Route::get('confirmed', 'Fece2Controller@Fece2Confirmed')->name('fece2s.confirmed');
    Route::post('fece2_meem7_attach_file', 'Fece2Controller@attachFileMeem7')->name('fece2_meem7_attach_file');
    Route::get('get_fece9_details/{id}', 'Fece9Controller@getFece9Details')->name('fece9s.get_fece9');

    Route::get('meem7/get_meem7_item_details_specifications/{meem7_id}', 'Meem7Controller@getMeem7ItemDetailsSpecifications')->name('meem7.get_meem7_item_details_specifications');
    Route::get('meem7/get_meem7_extra_specifications/{meem7_id}', 'Meem7Controller@getMeem7ExtraSpecifications')->name('meem7.get_meem7_item_details_specifications');
    Route::get('create_meem7/{fece9_id}', 'Meem7Controller@createMeem7')->name('meem7.create_meem7');
    Route::get('create_meem7_ghair_zakhirawi/{department_id}/{month}/{fece9_type}', 'Meem7Controller@createMeem7GhairZakhirawi')->name('meem7.create_meem7_ghair_zakhirawi');
    Route::get('meem7_completed', 'Meem7Controller@completed')->name('meem7.completed');
    // Route::get('meem7_show/meem7_id', 'Meem7Controller@meem7Show')->name('meem7_show');
    Route::resource('meem7', 'Meem7Controller');


    Route::resource('fece5s', 'Fece5Controller');
    Route::resource('motamed', 'MotamedController');
    Route::resource('motamed_type', 'MotamedTypeController');
    Route::get('get_motamed_type_allotments_ajax', 'MotamedTypeController@getMotamedTypeAjax')->name('get_motamed_type_allotments_ajax');
    Route::get('get_motameds', 'MotamedController@getMotameds')->name('get_motameds');
    Route::post('get_motamed_type_search', 'MotamedTypeController@getMotamedTypeSearch')->name('get_motamed_type_search');
    

    Route::post('allotments', 'AllotmentController@store')->name('allotments');
    Route::get('allotments/get_employees_allotments', 'AllotmentController@getEmployeesAllotments')->name('allotments.get_employees_allotments');
    Route::get('allotments/motamed_allotments', 'AllotmentController@getMotamedAllotments')->name('allotments.motamed_allotments');
    Route::get('allotments/get_employees_allotments_ajax', 'AllotmentController@getEmployeesAllotmentsAjax')->name('allotments.get_employees_allotments_ajax');
    Route::get('allotments/get_motamed_allotments_ajax', 'AllotmentController@getMotamedAllotmentsAjax')->name('allotments.get_motamed_allotments_ajax');
    Route::post('allotments/get_employees_allotments_search/{type?}', 'AllotmentController@getEmployeesAllotmentsSearch')->name('allotments.get_employees_allotments_search');
    Route::get('allotments/get_employee_allotments/{id}/{type}/{status?}', 'AllotmentController@getEmployeeAllotments')->name('allotments.get_employee_allotments');
    Route::get('allotments/get_motamed_allotments/{id}/{status?}', 'MotamedController@getMotamedAllotments')->name('allotments.get_motamed_allotments');
    Route::get('allotments/get_item_details_specifications_allotment_history/{item_details_specifications_id}/{item_balances_id?}', 'AllotmentController@getItemDetailsSpecificationsAllotmentHistory')->name('allotments.get_item_details_specifications_allotment_history');
    Route::get('allotments/get_item_details_specifications_allotment_active/{item_details_specifications_id}/{item_balances_id?}', 'AllotmentController@getItemDetailsSpecificationsAllotmentActive')->name('allotments.get_item_details_specifications_allotment_active');
    Route::get('allotments/role_back_allotment/{allotment_id}/{item_details_specifications_id}', 'AllotmentController@roleBackAllotement')->name('allotments.role_back_allotment');
    Route::get('allotments/get_item_details_specifications/{item_details_specifications_id}', 'AllotmentController@getItemDetailsSpecifications')->name('allotments.get_item_details_specifications');
    Route::get('allotments/get_all_item_details_specifications/{employee_id}', 'AllotmentController@getAllItemDetailsSpecifications')->name('allotments.get_all_item_details_specifications');
    Route::post('allotment/merge_duplicate_items/{employee_id}/{employee_type}','AllotmentController@mergeDuplicateItems')->name('merge_duplicate_items');
    // Route::resource('external_employee', 'ExternalEmployeeController');
    Route::prefix('allotments')->group(function () {
        Route::resource('external_employee', 'ExternalEmployeeController');
    });
    Route::get('get_external_employee_ajax', 'ExternalEmployeeController@getExternalEmployeeAjax')->name('external_employee.get_external_employee_ajax');
    Route::post('get_external_employees_search', 'ExternalEmployeeController@getExternalEmployeesSearch')->name('external_employee.get_external_employees_search');
    Route::get('get_external_employee/{id}', 'ExternalEmployeeController@getExternalEmployee')->name('get_external_employee');
    Route::post('get_motamed', 'AllotmentController@getMotamed')->name('get_motamed');

    Route::resource('item_return_requests', 'ItemReturnRequesdController');
    Route::get('item_return_requests_completed','ItemReturnRequesdController@completed')->name('item_return_requests.completed');
    Route::get('item_return_requests_inprogress','ItemReturnRequesdController@inprogress')->name('item_return_requests.inprogress');
    Route::post('item_return_requests/conformation/{id}', 'ItemReturnRequesdController@itemReturnConformation')->name('item_return_requests.conformation');
    Route::post('attach_file_requested_item', 'ItemReturnRequesdController@attachFileAndSend')->name('attach_file_requested_item');
    Route::post('replace_return_requests_file', 'ItemReturnRequesdController@replaceAttachedFile')->name('replace_return_requests_file');


    Route::group(['prefix' => 'fece5s', 'as' => 'fece5s.'], function () {
        Route::post('attach_file_and_send', 'Fece5Controller@attachFileAndSend')->name('attach_file_and_send');
        Route::post('replace_attached_file', 'Fece5Controller@replaceAttachedFile')->name('replace_attached_file');
        Route::get('conformation/{id?}/{status?}', 'Fece5Controller@fece5Conformation')->name('conformation');
        Route::post('reject_fece5/{id?}', 'Fece5Controller@rejectFece5')->name('reject_fece5');
    });

    Route::post('export_excel','ReportController@exportExcel')->name('export_excel');

    // Route::group(['prefix' => 'items', 'as' => 'items.'], function() {
    //     Route::get('/', 'ItemDetailsController@index')->name('index');
    //
    // });
    // Route::resource('end_items_details', 'ItemDetailsController');

    // Settings

    // Unit
    Route::resource('units', 'UnitController');
    Route::resource('contractor_company', 'ContractorCompanyController');
    Route::resource('contracts', 'ContractController');
    Route::get('contracts_show_item/{id?}', 'ContractController@contractsShowItem')->name('contracts.show_item');
    Route::resource('contract_type', 'ContractTypeController');
    Route::resource('contract_items', 'ContractItemsController');

    // Department

app/Fece9.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;

class Fece9 extends Model
{
    use LogsActivity;
    use SoftDeletes;
    use PivotEventTrait;


    protected $fillable = ['number', 'date',  'description','text','reject_remark', 'department_id', 'processed_fece9_file', 'fece9_type', 'inspection_approval','independent_unit', 'status', 'created_by', 'updated_by', 'deleted_by'];

    protected static $logAttributes = ['number', 'date',  'description','text','reject_remark', 'department_id', 'processed_fece9_file', 'fece9_type', 'inspection_approval','independent_unit', 'status', 'created_by', 'updated_by', 'deleted_by'];

    public function department()
    {
        return $this->belongsTo('App\Department');
    }


    public function fece5s()
    {
        return $this->hasMany('App\Fece5');
    }

    public function meem7()
    {
        return $this->hasOne('App\Meem7', 'fece9_id', 'id');
    }

    public function itemDetails()
    {
        return $this->belongsToMany('App\ItemDetails')->with('unit')->withPivot('id', 'name', 'quantity', 'status', 'distributed', 'created_by', 'updated_by', 'deleted_by')->withTimestamps();
    }

    public function fece5ItemDetails()
    {
        return $this->hasMany('App\ItemDetailsSpecifications', 'fece9_id', 'id');
    }
    
    public function fece9ItemDetails()
    {
        return $this->hasMany('App\Fece9ItemDetails', 'fece9_id', 'id');
    }



    public static function boot()
    {
        parent::boot();

        // static::attach(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
        //     activity()
        //     ->performedOn($model)
        //     ->causedBy(auth()->user())
        //     ->withProperties($pivotIdsAttributes)
        //     ->log('Look, I logged something');
        // });
        static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
            if ($relationName == 'itemDetails') {
                activity()
                    ->performedOn($model)
                    ->causedBy(auth()->user())
                    ->withProperties($pivotIdsAttributes)
                    ->log($relationName);
            }
        });
        // create a event to happen on updating
        static::updating(function ($table) {
            $table->updated_by = Auth::user()->id ;
        });

        // create a event to happen on deleting
        static::deleting(function ($table) {
            $table->deleted_by = Auth::user()->id ;
        });

        // create a event to happen on saving
        static::saving(function ($table) {
            $table->created_by = Auth::user()->id ;
        });
    }
}

resources/views/fece9s/proper/edit.blade.php
@extends('layouts.master')
@section('title', trans('global.edit_fece9'))
@section('content')
<form class="form" action="{{route('fece9s.update', $fece9->id)}}" method="POST">
    @csrf
    @method('PATCH')
    <div class="form-group m-form__group row ">
      <div class="form-group col-md-6 {{$errors->has('number') ? 'has-danger' : ''}}">
        <label for="fece9_number">{{trans('global.fece9_number')}}</label>
        <input type="text" name="number" value="{{$fece9->number}}" class="form-control m-input m-input--square" id="number" placeholder="نمبر ف س ۹ را وارید نماید.">
        @if($errors->has('number'))
            <div class="form-control-feedback">{{$errors->first('number')}}</div>
        @endif
      </div>

      <div class="form-group col-md-3 {{$errors->has('date') ? 'has-danger' : ''}}">
        <label for="inputPassword4">{{trans('global.fece9_date')}}</label>
         <div class="input-group date">
            <input type="text" name="date" value="{{$fece9->date}}" class="form-control persian_date" placeholder="تاریخ انتخاب کنید.">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="la la-calendar"></i>
              </span>
            </div>
        </div>
        @if($errors->has('date'))
          <div class="form-control-feedback">{{$errors->first('date')}}</div>
        @endif
      </div>
      <div class="form-group col-md-3 {{$errors->has('fece9_type') ? 'has-danger' : ''}}">
        <label for="inputPassword4">{{trans('global.fece9_type')}}</label>
            <select class="form-control" name="fece9_type">
                {{-- <option value="">{{trans('global.fece9_type')}}</option> --}}
                <option value="0" {{$fece9->fece9_type =='0' ? 'selected' :''}}>یومیه</option>
                <option value="1" {{$fece9->fece9_type =='1' ? 'selected' :''}}>ذخیروی</option>
                <option value="2" {{$fece9->fece9_type =='2' ? 'selected' :''}}>غیر ذخیروی</option>
                <option value="3" {{$fece9->fece9_type =='3' ? 'selected' :''}}>غیر مصرفی</option>
            </select>
        @if($errors->has('fece9_type'))
          <div class="form-control-feedback">{{$errors->first('fece9_type')}}</div>
        @endif
      </div>

    </div>
    <div class="form-group m-form__group row">
            <div class=" col-md-6 items_list {{$errors->has('list') ? 'has-danger' : ''}}">

                <div class="form-group">
                    <label for="inputState">{{trans('global.sub_category')}}</label>
                    <select id="sub_category_id" onchange="submitItemSpecifications()" name="sub_category_id" ref="item_details_id" class="form-control">
                        <option value="none" selected>یگ گزینه را انتخاب نماید .</option>
                        @foreach ($sub_category as $value)
                            <option value="{{$value->id}}"  {{old('sub_category_id') == $value->id ? 'selected' : ''}}>{{$value->name_dr}}</option>
                        @endforeach
                    </select>
                </div>


                </div>
        <div class="form-group col-md-6 {{$errors->has('department_id') ? 'has-danger' : ''}}">
            <label for="department">{{trans('global.requesting_department')}}</label>
            <select class="form-control select2" name="department_id" id="department">
                @foreach ($departments as $item)
                <option value="{{$item->id}}" {{$fece9->department_id == $item->id ? 'selected' : ''}}>{{$item->name_dr}}</option>
                @endforeach
            </select>
            @if($errors->has('department_id'))
                <div class="form-control-feedback">{{$errors->first('department_id')}}</div>
            @endif
        </div>
      </div>
      <div class="col-md-6" id="app">
            <div class="row items_list {{$errors->has('list') ? 'has-danger' : ''}}">
                <div class="form-group col-md-4">
                    <label for="item_details">{{trans('global.item')}}</label>
                    <select id="item_details" name="item" ref="item_details_id" class="form-control">
                        <option value="none" selected>یگ گزینه را انتخاب نماید.</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">{{trans('global.quantity')}}</label>
                    <input type="number" ref="quantity" name="quantity" class="form-control" min="1" placeholder="{{trans('global.quantity')}}">
                </div>
                <div class="form-group col-md-4">
                        <button type="button" v-on:click="addToList()" id="add_to_list" class="btn btn-outline-brand btn-square add-btn position-absolute" style="bottom:0;">+ اضافه نمودن</button>
                </div>

                @if($errors->has('list'))
                    <div class="form-control-feedback">{{$errors->first('list')}}</div>
                @endif
            </div>
            <div class="row">
                <table class="table items_table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>جنس</th>
                            <th>مقدار</th>
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{-- @foreach ($items_list as $index => $item)
                            <tr id="item_{{++$index}}">
                                <td>{{$index}}</td>
                                <td>{{$item['name']}}</td>
                                <td>{{$item['quantity']}}</td>
                                <td>
                                    <a href="javascript:void(0)" onclick="deleteItem({{$index}})" class="text-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        @endforeach --}}
                        <tr v-for="(item, index) in list">
                            <td>@{{index+1}}</td>
                            <td>@{{item.name}}</td>
                            <td>@{{item.quantity}}</td>
                            <td>
                                <a href="javascript:void(0)" v-on:click="removeFromList(index)" class="text-danger"><i class="fa fa-trash"></i></a>
                            </td>

                        </tr>
                    </tbody>
                </table>
                <input type="hidden" name="list" v-model="JSON.stringify(list)"  multiple>

            </div>
        </div>
      {{-- <input type="hidden" name="list" value='' multiple> --}}
      <input type="hidden" name="updated_by" value='{{auth()->user()->id}}' >
    <div class="form-group m-form__group row {{$errors->has('description') ? 'has-danger' : ''}}">
      <label for="inputAddress2">توضیحات</label>
      <textarea class="form-control" name="description" id="" rows="7">{{$fece9->description}}</textarea>
        @if($errors->has('description'))
            <div class="form-control-feedback">{{$errors->first('description')}}</div>
        @endif
    </div>

    <button type="submit" class="btn btn-primary">
        ذخیره
    </button>

    <a type="button" href="{{url('fece9/index')}}" class="btn btn-default">
        برگشت
    </a>

  </form>
@endsection
@push('custom-js')
    <script>
     
        // list = {!! $items_list ? json_encode($items_list, true) : '[]'  !!}
        // $(function() {
        //     $('input[name=list]').val(JSON.stringify(list));
        // })
        // console.log(list);
        // $('#add_to_list').click(function() {
        //     item = $('select[name=item] option:selected').val();
        //     name = $('select[name=item] option:selected').text();
        //     quantity = $('input[name=quantity]').val();
        //     if((item != 'none' && quantity != "")) {
        //         if(!(list.some(test => test.item_details_id == item))) {
        //             list.push({'item_details_id': item, 'name': name, 'quantity': quantity});
        //             $('.items_table > tbody:last-child').append('<tr id="item_'+list.length+'"><td>'+list.length+'</td><td>'+name+'</td><td>'+quantity+'</td><td><a href="javascript:void(0)" onclick="deleteItem('+list.length+')" class="text-danger"><i class="fa fa-trash"></i></a></td></tr>')
        //             $('select[name=item]').val('none').trigger('change');
        //             $('input[name=quantity]').val('');

        //             $('input[name=list]').val(JSON.stringify(list));

        //             $('select[name=item]').val('none').trigger('change');

        //             $('.items_list').removeClass('has-danger');
        //             $('.item_error').removeClass('d-block').addClass('d-none');
        //             $('.duplicate_item_error').removeClass('d-block').addClass('d-none');
        //         }
        //         else {
        //             $('.items_list').addClass('has-danger');
        //             $('.duplicate_item_error').removeClass('d-none').addClass('d-block');

        //         }
        //     }
        //     else {
        //         $('.items_list').addClass('has-danger');
        //         $('.item_error').removeClass('d-none').addClass('d-block');

        //     }
        //     // if(list.some(item => item.item_details_id != item)) {
        //     //     list.push({'item_details_id': item, 'quantity': quantity});
        //     //     console.log('hey');
        //     // }
        //     // $('.items_table > tbody:last-child').append('<tr id="item_'+list.length+'"><td>'+list.length+'</td><td>'+name+'</td><td>'+quantity+'</td><td><a href="javascript:void(0)" onclick="deleteItem('+list.length+')" class="text-danger"><i class="fa fa-trash"></i></a></td></tr>')

        //     // $('select[name=item]').val('none').trigger('change');
        //     // $('input[name=quantity]').val('');

        //     // $('input[name=list]').val(JSON.stringify(list));
        //     // console.log($('input[name=list]').val());

        // });

        // function deleteItem(id) {
        //     $('tr#item_'+id).remove();
        //     list.splice(id-1, 1);
        //     $('input[name=list]').val(JSON.stringify(list));
        //     console.log($('input[name=list]').val());

        // }
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Hello Vue!',
                list: {!! $items_list ? json_encode($items_list, 1) : '[]'  !!}
            },
            methods: {
                addToList: function(event) {

                        id = this.$refs.item_details_id.value

                        quantity = this.$refs.quantity.value

                        name = this.$refs.item_details_id.options[this.$refs.item_details_id.options.selectedIndex].text

                        let itemInList = this.list.filter(item => item.item_details_id===id);
                        let isItemInList = itemInList.length > 0;

                        if (isItemInList === false && id != 'none' && quantity != "") {
                            this.list.push({item_details_id: id, name: name, quantity: quantity })
                        }
                },

                removeFromList: function(index) {
                    this.list.splice(index, 1);
                }
            },
        })

        $('#sub_category_id').change(function() {
            sub_category_id = $(this).val();
            getSubCategoryKeys(sub_category_id);
        })



        function getSubCategoryKeys(sub_category_id, data) {
            console.log(data);
            $.ajax({
                method:'GET',
                url: '{{url("get_sub_categories_select_options")}}/'+sub_category_id,
                data: {data},
                success: function(resp) {
                    $('#keys_response').html(resp);
                }
            })
        }

        function submitItemSpecifications() {
            col1 = $('#col1').val();
            col2 = $('#col2').val();
            col3 = $('#col3').val();
            col4 = $('#col4').val();
            col5 = $('#col5').val();
            col6 = $('#col6').val();
            col7 = $('#col7').val();
            col8 = $('#col8').val();
            col9 = $('#col9').val();
            col10 = $('#col10').val();
            col11 = $('#col11').val();
            col12 = $('#col12').val();
            sub_category_id = {!! old('sub_category_id') ? old('sub_category_id') : "$('#sub_category_id').val();" !!}

            $.ajax({
                method: 'get',
                url: "{{url('get_item_details_by_specifications')}}/"+sub_category_id,
                data: {'col1': col1, 'col2': col2, 'col3': col3, 'col4': col4,'col5': col5,'col6': col6,'col7': col7,'col8': col8
                ,'col9': col9,'col10': col10,'col11': col11 ,'col12': col12},
                success: function(resp) {
                    console.log(resp);
                    $('#item_details').html('');
                    $.each(resp, populateOptions)
                }
            })
            $('#modal_sub_category_id').val(sub_category_id);
            console.log(sub_category_id+" - "+col1+" - "+col2+" - "+col3+" - "+col4);
        }

        function populateOptions(index, item) {
            $('#item_details').append('<option value="'+item.id+'">'+item.name_dr+'</option>');
        }


        $(function() {
           {!! old('sub_category_id') ? "submitItemSpecifications(); getSubCategoryKeys(".old('sub_category_id').");" : '' !!}
        })
    </script>

@endpush

resources/views/fece9s/proper/index.blade.php
@extends('layouts.master')
@section('title','ف س ۹')
@section('content')

<table id="example" class="table table-striped table-bordered jquery-datatable" style="width:100%">
    <thead>
        <tr>
            <th>#</th>
            <th>شماره</th>
            <th>تاریخ</th>
            <th>ریاست</th>
            <th>{{trans('global.fece9_type')}}</th>
            <th>اپلود فایل</th>
            <th>توضیحات</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($fece9s as $item)
        @php
        $i=1;
        @endphp
        <tr id='{{$item->id}}_tr'>
            <td>{{$i++}}</td>
            <td>{{$item->number}}</td>
            <td>{{$item->date}}</td>
            <td>{{$item->department->name_dr}}</td>
            <td>
                @php
                switch($item->fece9_type){
                    case 0 :
                        echo "یومیه";
                        break;
                    case 1 :
                        echo "ذخیروی";
                        break;
                    case 2 :
                        echo "غیر ذخیروی";
                        break;
                    case 3 :
                        echo "غیر مصرفی";
                        break;

                }

                @endphp
            </td>
            <td>
                @if ($item->status == 0)
                <a href="javascript:void(0)" data-toggle="modal" data-target="#upload_modal"
                    onclick="$('input[name=id]').val({{$item->id}})"
                    class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="fa fa-upload"></i>
                </a>
                @else
                <a href="javascript:void(0)"
                    class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="fa fa-check"></i>
                </a>
                @endif
            </td>
            <td>{{str_limit($item->description,50)}}</td>
            <td>
                <a href="{{route('fece9s.show',$item->id)}}"
                    class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="la la-eye"></i>
                </a>
                <a href="{{route('fece9s.edit', $item->id)}}"
                    class="btn btn-outline-brand m-btn m-btn--icon btn-sm m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="la la-edit"></i>
                </a>
                <a href="{{route('fece9_print', $item->id)}}"
                    class="btn btn-outline-brand m-btn m-btn--icon btn-sm m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="la la-print"></i>
                </a>
                <a href="javascript:void(0)"
                    onclick="deleteRecord('{{route('fece9s.destroy', $item->id)}}','{{$item->id}}_tr');"
                    class="btn btn-outline-brand m-btn m-btn--icon btn-sm m-btn--icon-only m-btn--pill m-btn--air">
                    <i class="la la-trash"></i>
                </a>
            </td>
        </tr>
        @endforeach
</table>
{{-- Start of the Modal  --}}
<!-- Modal -->
<div class="modal fade" id="upload_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">اپلود نمودن ف س ۹ طی مراحل شده</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('fece9s.attach_file_and_send')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-group m-form__group col-lg-12">
                        <div></div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" multiple name="image" ref="file">
                            <label class="custom-file-label" for="customFile">انتخاب فایل</label>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="id" value="">
                <div class="modal-footer">
                    <div class="row">

                        <div class="col-md-6">
                            <div class="btn-group m-btn-group" role="group" aria-label="...">
                                <button type="submit" class="btn btn-brand">ارسال <i
                                        class="la la-paperclip"></i></button>
                                <button type="button" class="btn btn btn-info" data-dismiss="modal">لغو</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{{-- End of the Modal  --}}
@endsection