routes/web.php
    Route::get('create_meem7_ghair_zakhirawi/{department_id}/{month}/{fece9_type}', 'Meem7Controller@createMeem7GhairZakhirawi')->name('meem7.create_meem7_ghair_zakhirawi');
    Route::get('meem7_completed', 'Meem7Controller@completed')->name('meem7.completed');
    // Route::get('meem7_show/meem7_id', 'Meem7Controller@meem7Show')->name('meem7_show');
    Route::resource('meem7', 'Meem7Controller');


    Route::resource('fece5s', 'Fece5Controller');
    Route::resource('motamed', 'MotamedController');
    Route::resource('motamed_type', 'MotamedTypeController');
    Route::get('get_motamed_type_allotments_ajax', 'MotamedTypeController@getMotamedTypeAjax')->name('get_motamed_type_allotments_ajax');
    Route::get('get_motameds', 'MotamedController@getMotameds')->name('get_motameds');
    Route::post('get_motamed_type_search', 'MotamedTypeController@getMotamedTypeSearch')->name('get_motamed_type_search');
    

    Route::post('allotments', 'AllotmentController@store')->name('allotments');
    Route::get('allotments/get_employees_allotments', 'AllotmentController@getEmployeesAllotments')->name('allotments.get_employees_allotments');
    Route::get('allotments/motamed_allotments', 'AllotmentController@getMotamedAllotments')->name('allotments.motamed_allotments');
    Route::get('allotments/get_employees_allotments_ajax', 'AllotmentController@getEmployeesAllotmentsAjax')->name('allotments.get_employees_allotments_ajax');
    Route::get('allotments/get_motamed_allotments_ajax', 'AllotmentController@getMotamedAllotmentsAjax')->name('allotments.get_motamed_allotments_ajax');
    Route::post('allotments/get_employees_allotments_search/{type?}', 'AllotmentController@getEmployeesAllotmentsSearch')->name('allotments.get_employees_allotments_search');
    Route::get('allotments/get_employee_allotments/{id}/{type}/{status?}', 'AllotmentController@getEmployeeAllotments')->name('allotments.get_employee_allotments');
    Route::get('allotments/get_motamed_allotments/{id}/{status?}', 'MotamedController@getMotamedAllotments')->name('allotments.get_motamed_allotments');
    Route::get('allotments/get_item_details_specifications_allotment_history/{item_details_specifications_id}/{item_balances_id?}', 'AllotmentController@getItemDetailsSpecificationsAllotmentHistory')->name('allotments.get_item_details_specifications_allotment_history');
    Route::get('allotments/get_item_details_specifications_allotment_active/{item_details_specifications_id}/{item_balances_id?}', 'AllotmentController@getItemDetailsSpecificationsAllotmentActive')->name('allotments.get_item_details_specifications_allotment_active');
    Route::get('allotments/role_back_allotment/{allotment_id}/{item_details_specifications_id}', 'AllotmentController@roleBackAllotement')->name('allotments.role_back_allotment');
    Route::get('allotments/get_item_details_specifications/{item_details_specifications_id}', 'AllotmentController@getItemDetailsSpecifications')->name('allotments.get_item_details_specifications');
    Route::get('allotments/get_all_item_details_specifications/{employee_id}', 'AllotmentController@getAllItemDetailsSpecifications')->name('allotments.get_all_item_details_specifications');
    Route::post('allotment/merge_duplicate_items/{employee_id}/{employee_type}','AllotmentController@mergeDuplicateItems')->name('merge_duplicate_items');
    // Route::resource('external_employee', 'ExternalEmployeeController');
    Route::prefix('allotments')->group(function () {
        Route::resource('external_employee', 'ExternalEmployeeController');
    });
    Route::get('get_external_employee_ajax', 'ExternalEmployeeController@getExternalEmployeeAjax')->name('external_employee.get_external_employee_ajax');
    Route::post('get_external_employees_search', 'ExternalEmployeeController@getExternalEmployeesSearch')->name('external_employee.get_external_employees_search');
    Route::get('get_external_employee/{id}', 'ExternalEmployeeController@getExternalEmployee')->name('get_external_employee');
    Route::post('get_motamed', 'AllotmentController@getMotamed')->name('get_motamed');

    Route::resource('item_return_requests', 'ItemReturnRequesdController');
    Route::get('item_return_requests_completed','ItemReturnRequesdController@completed')->name('item_return_requests.completed');
    Route::get('item_return_requests_inprogress','ItemReturnRequesdController@inprogress')->name('item_return_requests.inprogress');
    Route::post('item_return_requests/conformation/{id}', 'ItemReturnRequesdController@itemReturnConformation')->name('item_return_requests.conformation');
    Route::post('attach_file_requested_item', 'ItemReturnRequesdController@attachFileAndSend')->name('attach_file_requested_item');
    Route::post('replace_return_requests_file', 'ItemReturnRequesdController@replaceAttachedFile')->name('replace_return_requests_file');


    Route::group(['prefix' => 'fece5s', 'as' => 'fece5s.'], function () {
        Route::post('attach_file_and_send', 'Fece5Controller@attachFileAndSend')->name('attach_file_and_send');
        Route::post('replace_attached_file', 'Fece5Controller@replaceAttachedFile')->name('replace_attached_file');
        Route::get('conformation/{id?}/{status?}', 'Fece5Controller@fece5Conformation')->name('conformation');
        Route::post('reject_fece5/{id?}', 'Fece5Controller@rejectFece5')->name('reject_fece5');
    });

    Route::post('export_excel','ReportController@exportExcel')->name('export_excel');

    // Route::group(['prefix' => 'items', 'as' => 'items.'], function() {
    //     Route::get('/', 'ItemDetailsController@index')->name('index');
    //
    // });
    // Route::resource('end_items_details', 'ItemDetailsController');

    // Settings

    // Unit
    Route::resource('units', 'UnitController');
    Route::resource('contractor_company', 'ContractorCompanyController');
    Route::resource('contracts', 'ContractController');
    Route::get('contracts_show_item/{id?}', 'ContractController@contractsShowItem')->name('contracts.show_item');
    Route::resource('contract_type', 'ContractTypeController');
    Route::resource('contract_items', 'ContractItemsController');

    // Department
    Route::resource('departments', 'DepartmentController');
    Route::get('get_departments', 'DepartmentController@getDepartment')->name('get_departments');
    Route::resource('external_departments', 'ExternalDepartmentController');
    

    // Sub Categories Keys
    Route::get('sub_categories_keys/create/{sub_categories_id?}', 'SubCategoriesKeyController@create')->name('sub_categories_keys.create');
    Route::resource('sub_categories_keys', 'SubCategoriesKeyController')->except('create');
    Route::get('get_sub_categories_keys/{sub_category_id?}/{data?}', 'SubCategoriesKeyController@getSubCategoriesKeys')->name('sub_categories_keys.get_sub_categories_keys');
    Route::get('get_sub_categories_select_options/{sub_category_id?}/{data?}', 'SubCategoriesKeyController@getSubCategoriesSelectOptions')->name('sub_categories_keys.get_sub_categories_select_options');
    Route::get('get_item_details_by_specifications/{sub_category_id?}', 'SubCategoriesKeyController@getItemDetailsBySpecifications')->name('sub_categories_keys.get_item_details_by_specifications');

    // Vendor
    Route::resource('vendors', 'VendorController');

    // Main Category
    Route::resource('main_categories', 'MainCategoryController');
    Route::post('get_sub_categories', 'MainCategoryController@getSubCategories')->name('get_sub_categories');
    Route::post('get_end_categories', 'MainCategoryController@getEndCategories')->name('get_end_categories');
    Route::resource('sub_categories', 'SubCategoryController');
    Route::resource('end_categories', 'EndCategoryController');

    Route::post('get_setting_modal_view', 'ItemDetailsController@getSettingModalView')->name('get_setting_modal_view');

    // testing the new items format
    // Route::get('item_details/create_new_items', 'ItemDetailsController@createNewItems')->name('item_details.create_new_items');
    Route::get('get_categories', 'ItemDetailsController@getCategories')->name('get_categories');
    Route::post('get_related_categories', 'ItemDetailsController@getRelatedCategories')->name('get_related_categories');
    Route::get('get_all_employees', 'EmployeeController@getAllEmployees')->name('get_all_employees');
    Route::get('get_employees_by_dep/{department_id}', 'EmployeeController@getEmployeesByDep')->name('get_all_employees');
    Route::get('get_employees_by_father/{father_name}', 'EmployeeController@getEmployeesByFather')->name('get_employees_by_father');
    Route::get('get_employees_by_name_father/{employee_type?}/{name?}/{father_name?}', 'EmployeeController@getEmployeesByNameFather')->name('get_employees_by_name_father');

    Route::resource('item_details', 'ItemDetailsController');
    Route::get('get_item_details', 'ItemDetailsController@getItemDetails')->name('get_item_details');
    Route::get('get_item_details_ajax', 'ItemDetailsController@getItemDetailsAjax')->name('get_item_details_ajax');
    Route::post('item_details_search', 'ItemDetailsController@itemDetailsSearch')->name('item_details_search');
    Route::get('get_item_details_consumable', 'ItemDetailsController@getItemDetailsConsumable')->name('get_item_details_consumable');

    // check if all requested items alloted based on item_details_id
    Route::get('fece9_all_items_alloted/{fece9_id}/{item_details_id}', 'ItemDetailsController@fece9AllItemsAlloted')->name('item_details.fece9_all_items_alloted');

    Route::resource('item_details_specifications', 'ItemDetailsSpecificationsController');
    Route::get('edit_item_details_specifications/{id}/', 'ItemDetailsSpecificationsController@editItemDetailsSpecifications')->name('item_details_specifications.edit_item_details_specifications');

app/ExternalEmployee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\SoftDeletes;

class ExternalEmployee extends Model
{
    use LogsActivity;
    use SoftDeletes;
    protected $table = 'external_employee';
    protected $fillable = ['name_dr','name_en','father_name_dr','father_name_en','last_name','current_position_dr','current_position_en','external_department_id','created_at','updated_at','created_by','updated_by','deleted_at','deleted_by'];
    protected static $logAttributes = ['name_dr','name_en','father_name_dr','father_name_en','last_name','current_position_dr','current_position_en','external_department_id','created_at','updated_at','created_by','updated_by','deleted_at','deleted_by'];
    public function allotments() {
        return $this->hasMany('App\Allotment','receiver_employee_id','id')->where('employee_type',1);
    }
    public function employee_attachments() {
        return $this->hasMany('App\EmployeeAttachment','employee_id','id');
    }
    protected static function boot()
    {
        parent::boot();

        // create a event to happen on updating
        static::updating(function($table)  {
            $table->updated_by = Auth::user()->id ;
        });

        // create a event to happen on deleting
        static::deleting(function($table) {
            $table->deleted_by = Auth::user()->id ;
        });

        // create a event to happen on saving
        static::saving(function($table)  {
            $table->created_by = Auth::user()->id ;
        });
    }
    public function external_department() {
        return $this->belongsTo('App\ExternalDepartment');
    }
}

app/Http/Controllers/ExternalEmployeeController.php
<?php

namespace App\Http\Controllers;

use App\ExternalEmployee;
use App\ExternalDepartment;
use Illuminate\Http\Request;
use App\Http\Requests\StoreExternalEmployeeRequest;
use App\Http\Requests\UpdateExternalEmployeeREquest;
use Illuminate\Support\Facades\Auth;

class ExternalEmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $external_employee=ExternalEmployee::paginate(10);
        $external_departments = ExternalDepartment::all();
        return view('external-employee.index',compact('external_employee','external_departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $external_departments = ExternalDepartment::all();
        return view('external-employee.create',compact('external_departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreExternalEmployeeRequest $request)
    {
        $external_employee = ExternalEmployee::create($request->input());
        if($external_employee){
            return redirect()->route('external_employee.create')->with('success', trans('global.create_successful'));
        }       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       
        $external_employee=ExternalEmployee::find(decrypt($id));
        $external_departments = ExternalDepartment::all();
        return view('external-employee.edit',compact('external_employee','external_departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateExternalEmployeeREquest $request, $id)
    {
       
        $external_employee=ExternalEmployee::find(decrypt($id));
        $external_employee->update($request->input());
        return redirect()->route('external_employee.index')->with('success', trans('global.update_successful'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $external_employee=ExternalEmployee::find(decrypt($id));
        $external_employee->delete();
        $external_employee['deleted_by']=Auth::user()->id;
        $external_employee->save();
        return response()->json([
            'status'  => 'success',
            'message' => trans('global.delete_successful')
        ]);
    }
    public function getExternalEmployeeAjax(Request $request){
      
        if($request->ajax()){  
            $external_employee=ExternalEmployee::select('id','name_dr','father_name_dr','current_position_dr','external_department_id')->paginate(10);
            return view('external-employee.external_employee_list',compact('external_employee'))->render();
        }
    }
    public function getExternalEmployeesSearch (Request $request) {
    
        if($request->ajax()){
            $external_employee=ExternalEmployee::select('id','name_dr','father_name_dr','current_position_dr','external_department_id')
            ->where('name_dr','LIKE','%'.$request->name_dr.'%')
            ->where('father_name_dr','LIKE','%'.$request->father_name_dr.'%')
            ->where('current_position_dr','LIKE','%'.$request->current_position_dr.'%')
            ->where('external_department_id','LIKE','%'.$request->external_department_id.'%')
            ->paginate(100);
            return view('external-employee.external_employee_list',compact('external_employee'))->render();
        }
    }
    public function getExternalEmployee ($id) {
        
        $external_employee=ExternalEmployee::find(decrypt($id));
        return $external_employee;
    }

}

resources/views/external-employee/create.blade.php
@extends('layouts.master')
@section('title', trans('global.create_external_employee'))
@section('content')

<form class="m-form m-form--fit m-form--label-align-right" method="POST" action="{{route('external_employee.store')}}">
    @csrf
    <div class="m-portlet__body">
        <div class="form-group m-form__group {{$errors->has('external_department_id') ? 'has-danger' : ''}}">
            <label for="employee_id">اداره بیرونی</label>
            <select class="form-control select2 m-input m-input--square" name="external_department_id">
                <option value="">--انتخاب--</option>
                @foreach ($external_departments as $value)
                    <option {{old('external_department_id') == $value->id ? 'selected' : ''}} value="{{$value->id}}">نام دری&nbsp;&nbsp;({{$value->name_dr}})&nbsp;&nbsp;&nbsp;&nbsp; نام پشتو&nbsp;&nbsp; ({{$value->name_pa}}) </option>
                @endforeach
            </select>
            @if ($errors->has('external_department_id'))
                <div class="form-control-feedback">{{$errors->first('external_department_id')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_dr" value="{{old('name_dr')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name')}}">
            @if($errors->has('name_dr'))
                <div class="form-control-feedback">{{$errors->first('name')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('father_name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.father_name')}}</label>
            <input name="father_name_dr" value="{{old('father_name_dr')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.father_name')}}">
            @if($errors->has('father_name_dr'))
                <div class="form-control-feedback">{{$errors->first('father_name')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('current_position_dr') ? 'has-danger' : ''}}">
            <label for="department_name">عنوان وظیفه</label>
            <input name="current_position_dr" value="{{old('current_position_dr')}}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="عنوان وظیفه">
            @if($errors->has('current_position_dr'))
                <div class="form-control-feedback">{{$errors->first('current_position_dr')}}</div>
            @endif
        </div>
    </div>
    <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
            <button type="submit" class="btn btn-primary">{{trans('global.submit')}}</button>
            <button type="reset" class="btn btn-danger">{{trans('global.cancel')}}</button>
        </div>
    </div>
</form>
@endsection

resources/views/external-employee/edit.blade.php
@extends('layouts.master')
@section('title', trans('global.edit_external_employee'))
@section('content')

<form class="m-form m-form--fit m-form--label-align-right" method="POST" action="{{route('external_employee.update', encrypt($external_employee->id))}}">
    @csrf
    @method('PUT')
    <div class="m-portlet__body">
        <div class="form-group m-form__group {{$errors->has('name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.name')}}</label>
            <input name="name_dr" value="{{ $external_employee->name_dr }}" type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.name')}}">
            @if($errors->has('name_dr'))
                <div class="form-control-feedback">{{$errors->first('name_dr')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('father_name_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.father_name')}}</label>
            <input name="father_name_dr" value="{{ $external_employee->father_name_dr }}"  type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.father_name')}}">
            @if($errors->has('father_name_dr'))
                <div class="form-control-feedback">{{$errors->first('father_name_dr')}}</div>
            @endif
        </div>
        <div class="form-group m-form__group {{$errors->has('current_position_dr') ? 'has-danger' : ''}}">
            <label for="department_name">{{trans('global.designation')}}</label>
            <input name="current_position_dr" value="{{ $external_employee->current_position_dr }}"  type="text" class="form-control m-input m-input--square" id="department_name" aria-describedby="emailHelp" placeholder="{{trans('global.designation')}}">
            @if($errors->has('current_position_dr'))
                <div class="form-control-feedback">{{$errors->first('current_position_dr')}}</div>
            @endif
        </div>
    </div>
    <div class="form-group m-form__group {{$errors->has('external_department_id') ? 'has-danger' : ''}}">
        <label for="employee_id">اداره بیرونی</label>
        <select class="form-control select2 m-input m-input--square" name="external_department_id">
            <option value="">--انتخاب--</option>
            @foreach ($external_departments as $value)
                <option {{$external_employee->external_department_id == $value->id ? 'selected' : ''}} value="{{$value->id}}">نام دری&nbsp;&nbsp;({{$value->name_dr}})&nbsp;&nbsp;&nbsp;&nbsp; نام پشتو&nbsp;&nbsp; ({{$value->name_pa}}) </option>
            @endforeach
        </select>
        @if($errors->has('external_department_id'))
            <div class="form-control-feedback">{{$errors->first('external_department_id')}}</div>
        @endif
    </div>
</div>
    <div class="m-portlet__foot m-portlet__foot--fit">
        <div class="m-form__actions">
            <button type="submit" class="btn btn-primary">{{trans('global.submit')}}</button>
            <button type="reset" class="btn btn-danger">{{trans('global.cancel')}}</button>
        </div>
    </div>
</form>
@endsection

resources/views/external-employee/external_employee_list.blade.php
<table class="table table-striped- table-bordered table-hover table-checkable " id="m_table_1">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">{{trans('global.name')}}</th>
            <th scope="col">{{trans('global.father_name')}}</th>
            <th scope="col">{{trans('global.designation')}}</th>
            <th scope="col">{{trans('global.department')}}</th>
            <th scope="col">{{trans('global.actions')}}</th>
          </tr>
        </thead>
        <tbody>
            @php
                if(count($external_employee) ==0){
                    echo '<tr class="odd"><th valign="top" colspan="6" class="dataTables_empty text-center">معلومات مورد نظر دریافت نشد</th></tr>';
                }
            @endphp
            @foreach ($external_employee as $index => $item)
                <tr id="{{$item->id}}_tr">
                    <th scope="row">{{$item->id}}</th>
                    <td>{{$item->name_dr}} </td>
                    <td>{{$item->father_name_dr}}</td>
                    <td>{{$item->current_position_dr}}</td>
                    <td>
                      {{$item->external_department_id != 0 ? $item->external_department->name_dr :''}}
                    </td>
                    <td>
                        <a class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" href="{{ route('allotments.get_employee_allotments',[encrypt($item->id),'type'=>'1']) }}"><i class="la la-eye"></i></a>
                        <a class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" href="{{ route('external_employee.edit',encrypt($item->id)) }}"><i class="la la-edit"></i></a>
                        <a href="javascript:void(0)" onclick="deleteRecord('{{route('external_employee.destroy', encrypt($item->id))}}','{{$item->id}}_tr');" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill ">
                          <i class="fa fa-trash"></i>
                      </a>
                    </td>
                </tr>
            @endforeach
        </tbody>
</table>
    
 {!! $external_employee->links()!!}

resources/views/external-employee/index.blade.php
@extends('layouts.master')
@section('title',trans('global.external_employee'))
@section('content')
{{-- jquery-datatable --}}
<form action="" id="searchForm" >
<div class="row m--margin-bottom-20">
   
    <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
      <label>{{trans('global.name')}}:</label>
      <input type="text"   name="name_dr" class="form-control m-input" placeholder="{{trans('global.name')}}" data-col-index="0">
    </div>
    <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
      <label>{{trans('global.father_name')}}:</label>
      <input type="text"  id="father_name_dr" name="father_name_dr" class="form-control m-input" placeholder="{{trans('global.father_name')}}" data-col-index="1">
    </div>
  
    <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
      <label>{{trans('global.designation')}}:</label>
      <input type="text"  id="current_position_dr" name="current_position_dr" class="form-control m-input" placeholder="{{trans('global.designation')}}" data-col-index="4">
    </div>
    <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
      <label>{{trans('global.department')}}:</label>
      <select class="form-control select2 m-input m-input--square" name="external_department_id">
        <option value="">--انتخاب--</option>
        @foreach ($external_departments as $value)
            <option {{old('external_department_id') == $value->id ? 'selected' : ''}} value="{{$value->id}}">نام دری&nbsp;&nbsp;({{$value->name_dr}})&nbsp;&nbsp;&nbsp;&nbsp; نام پشتو&nbsp;&nbsp; ({{$value->name_pa}}) </option>
        @endforeach
    </select>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 mt-3">
        <button type="submit" id="searchButton" class="btn btn-info">
            <i class="fa fa-search"></i> جستجو
        </button>
    </div>
</div>
@push('create-button')
<a href="{{ route('external_employee.create') }}" class="btn btn-success m-btn m-btn--custom ">
    <span>
    <span>اضافه نمودن</span>
    <i class="la la-plus"></i>
    </span>
</a>
@endpush
</form>
  <div class="m-separator m-separator--md m-separator--dashed"></div>
  
<div id="data_table" class="table-responsive">
  
  @include('external-employee.external_employee_list')
</div>
@endsection
@push('custom-js')
<script>
  $.ajaxSetup({
  headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
  }
  });

  $(document).ready(function(){
    
    $(document).on('click','.pagination a',function(event){
      event.preventDefault();
      var page = $(this).attr('href').split('page=')[1];
      get_data(page);

    });
    function get_data(page){
      $.ajax({
          url:'{{url("")}}/get_external_employee_ajax?page='+page,
          beforeSend: function() {
        // setting a timeout
          $("#data_table").prepend('<div class="m-blockui "><span>لطفا منتظر باشید </span><span><div class="m-loader  m-loader--brand m-loader--lg"></div></span></div>');
          },
          success:function(data){
              $("#data_table").html(data);
          }
      });
    }   
  });

$(document).ready(function() {
    $('#searchForm').on('submit', function(event) {
      event.preventDefault(); // Prevent default form submission behavior

      // Retrieve form data
      var formData = $(this).serialize();

      // Construct the URL with the desired route
      var url = '{{ route("external_employee.get_external_employees_search") }}';
          // Get CSRF token from the meta tag
      var csrfToken = $('meta[name="csrf-token"]').attr('content');

      // Send AJAX request
      $.ajax({
        url: url,
        type: 'POST',
        data: formData,
        success: function(response) {
          // console.log(response)
          $("#data_table").html(response);
        },
        error: function(xhr, status, error) {
          // Handle error
        }
      });
    });
  });
</script>
@endpush
@push('custom-css')
    <style>
      #data_table .m-blockui {
        color: #5867dd;
        text-align: center !important;
        position: fixed;
        top: 30%;
        right: 50%;
        display: inline-table;
      }
    </style>  
@endpush